// ===== TYPES =====

export interface IOCase {
  firNumber: string;       // e.g. "FIR 142/2026"
  title: string;           // e.g. "State vs. Unknown"
  policeStation: string;
  dateRegistered: string;  // ISO string
  investigatingOfficer: string;
  evidenceCount: number;
  witnessCount: number;
  offences: string[];      // IPC sections, e.g. ["IPC 302", "IPC 201"]
  forensicProgress: { completed: number; total: number };
  cocStatus: 'Verified' | 'Pending' | 'Exception';
  status: 'Open' | 'Under Investigation' | 'Awaiting Forensics' | 'Charge Sheet Preparation' | 'Closed';
  lastUpdated: string;     // ISO string
  description: string;
  district: string;
}

export interface IOEvidence {
  evidenceId: string;         // e.g. "EV-0142"
  caseId: string;             // firNumber
  type: string;               // e.g. "Mobile Device", "Physical Sample", "CCTV Footage"
  description: string;
  collectedAt: string;        // ISO string
  collectedLocation: string;
  collectedBy: string;
  currentCustodian: string;
  currentLocation: string;
  status: 'Secure Storage' | 'At FSL' | 'In Transit' | 'Returned' | 'Disposed';
  integrityStatus: 'Verified' | 'Compromised' | 'Pending' | 'Not Checked';
  forensicStatus: 'Pending Submission' | 'In Transit' | 'Received by FSL' | 'Under Examination' | 'Examination Complete' | 'Report Available' | 'Not Required';
  sha256Hash: string;         // full 64-char hex
  blockchainTxId: string;     // e.g. "TX-8F21A4B9"
  blockchainVerified: boolean;
  sealId?: string;            // e.g. "SEAL-9821"
  notes?: string;
}

export interface CustodyEvent {
  id: string;
  evidenceId: string;
  timestamp: string;          // ISO string
  eventType: 'Evidence Collected' | 'Evidence Sealed' | 'Custody Transferred' | 'Custody Received' | 'Transferred to FSL' | 'Received by FSL' | 'Forensic Examination Started' | 'Forensic Report Filed' | 'Evidence Returned';
  actor: string;
  fromCustodian?: string;
  toCustodian?: string;
  location: string;
  txId: string;               // blockchain TX ID
  blockchainVerified: boolean;
  notes?: string;
  sealId?: string;
}

export interface ForensicRecord {
  evidenceId: string;
  caseId: string;
  fslRef: string;             // e.g. "FSL-BLR-2026-4421"
  fslName: string;            // e.g. "FSL Bengaluru"
  submittedDate: string;
  receivedDate?: string;
  examinationStartDate?: string;
  expectedCompletionDate?: string;
  completionDate?: string;
  examinationStatus: 'Pending Submission' | 'In Transit' | 'Received by FSL' | 'Under Examination' | 'Examination Complete' | 'Report Available';
  reportHash?: string;
  reportBlockchainTxId?: string;
  reportBlockchainVerified?: boolean;
  examiner?: string;
  findings?: string;
}

export interface IOAlert {
  id: string;
  severity: 'critical' | 'warning' | 'info';
  type: string;
  caseId: string;
  evidenceId?: string;
  title: string;
  description: string;
  timestamp: string;
  status: 'Open' | 'Acknowledged' | 'Resolved';
}

export interface AuditEvent {
  id: string;
  timestamp: string;
  user: string;
  action: string;
  evidenceId?: string;
  caseId?: string;
  txId: string;
  verificationStatus: 'Verified' | 'Pending' | 'Failed';
  details?: string;
  role?: string;
}

// ===== MOCK CASES =====

export const MOCK_CASES: IOCase[] = [
  {
    firNumber: 'FIR 142/2026',
    title: 'State vs. Unknown',
    policeStation: 'Central Police Station',
    dateRegistered: '2026-09-02T10:00:00.000Z',
    investigatingOfficer: 'SI Arun Kumar',
    evidenceCount: 17,
    witnessCount: 4,
    offences: ['IPC 302', 'IPC 201', 'IPC 120B'],
    forensicProgress: { completed: 15, total: 17 },
    cocStatus: 'Verified',
    status: 'Under Investigation',
    lastUpdated: '2026-09-15T14:22:00.000Z',
    description: 'Homicide case registered at Central PS, Bengaluru. Victim found at Koramangala residential area. Investigation ongoing; primary suspect yet to be identified. Multiple digital and physical evidence items collected from crime scene.',
    district: 'Bengaluru Urban',
  },
  {
    firNumber: 'FIR 089/2026',
    title: 'State vs. Ramesh Babu',
    policeStation: 'Koramangala PS',
    dateRegistered: '2026-07-15T08:30:00.000Z',
    investigatingOfficer: 'DSP Priya Menon',
    evidenceCount: 8,
    witnessCount: 3,
    offences: ['IPC 379', 'IPC 411'],
    forensicProgress: { completed: 8, total: 8 },
    cocStatus: 'Verified',
    status: 'Charge Sheet Preparation',
    lastUpdated: '2026-09-14T09:10:00.000Z',
    description: 'Theft and receiving stolen property case. Accused Ramesh Babu apprehended in possession of stolen goods valued at ₹4,80,000. All forensic examinations completed; charge sheet under preparation.',
    district: 'Bengaluru Urban',
  },
  {
    firNumber: 'FIR 201/2026',
    title: 'State vs. Multiple Accused',
    policeStation: 'HSR Layout PS',
    dateRegistered: '2026-09-08T11:45:00.000Z',
    investigatingOfficer: 'SI Vikram Nair',
    evidenceCount: 23,
    witnessCount: 7,
    offences: ['IPC 420', 'IPC 467', 'IPC 468', 'IT Act 66C'],
    forensicProgress: { completed: 10, total: 23 },
    cocStatus: 'Pending',
    status: 'Awaiting Forensics',
    lastUpdated: '2026-09-15T17:55:00.000Z',
    description: 'Large-scale financial fraud and identity theft involving multiple accused persons. Digital forensics ongoing on 13 seized electronic devices. Forgery of official documents also suspected.',
    district: 'Bengaluru Urban',
  },
  {
    firNumber: 'FIR 056/2026',
    title: 'State vs. Unknown',
    policeStation: 'Whitefield PS',
    dateRegistered: '2026-06-01T06:20:00.000Z',
    investigatingOfficer: 'Inspector Deepa Srinivas',
    evidenceCount: 5,
    witnessCount: 2,
    offences: ['IPC 376'],
    forensicProgress: { completed: 5, total: 5 },
    cocStatus: 'Verified',
    status: 'Charge Sheet Preparation',
    lastUpdated: '2026-09-12T13:40:00.000Z',
    description: 'Sexual assault case filed at Whitefield PS. All medical and forensic evidence collected and examined. Victim statement recorded. Case under judicial scrutiny; charge sheet being finalized.',
    district: 'Bengaluru Urban',
  },
  {
    firNumber: 'FIR 178/2026',
    title: 'State vs. Suresh Kumar',
    policeStation: 'Jayanagar PS',
    dateRegistered: '2026-08-20T21:15:00.000Z',
    investigatingOfficer: 'SI Rajan Pillai',
    evidenceCount: 12,
    witnessCount: 5,
    offences: ['IPC 302', 'IPC 34'],
    forensicProgress: { completed: 7, total: 12 },
    cocStatus: 'Pending',
    status: 'Under Investigation',
    lastUpdated: '2026-09-16T08:05:00.000Z',
    description: 'Homicide case with accused Suresh Kumar in custody. Act committed in furtherance of common intention with unknown accomplices. Forensic ballistics and trace evidence examination pending.',
    district: 'Bengaluru South',
  },
  {
    firNumber: 'FIR 033/2026',
    title: 'State vs. Unknown',
    policeStation: 'Indiranagar PS',
    dateRegistered: '2026-04-10T22:00:00.000Z',
    investigatingOfficer: 'DSP Kavitha Reddy',
    evidenceCount: 3,
    witnessCount: 1,
    offences: ['IPC 392'],
    forensicProgress: { completed: 3, total: 3 },
    cocStatus: 'Verified',
    status: 'Closed',
    lastUpdated: '2026-08-30T15:00:00.000Z',
    description: 'Robbery case. Accused identified through CCTV footage and apprehended within 72 hours. Final report filed. Case closed following conviction.',
    district: 'Bengaluru Urban',
  },
  {
    firNumber: 'FIR 215/2026',
    title: 'State vs. Multiple',
    policeStation: 'Electronic City PS',
    dateRegistered: '2026-09-10T16:30:00.000Z',
    investigatingOfficer: 'SI Mohan Das',
    evidenceCount: 9,
    witnessCount: 4,
    offences: ['IT Act 66', 'IT Act 66C', 'IPC 420'],
    forensicProgress: { completed: 2, total: 9 },
    cocStatus: 'Exception',
    status: 'Awaiting Forensics',
    lastUpdated: '2026-09-16T10:30:00.000Z',
    description: 'Cybercrime case involving unauthorized access to corporate servers and identity fraud. Hash integrity mismatch detected on EV-0215. Chain-of-custody exception raised; internal review initiated.',
    district: 'Bengaluru Urban',
  },
  {
    firNumber: 'FIR 067/2026',
    title: 'State vs. Anand Varma',
    policeStation: 'Shivajinagar PS',
    dateRegistered: '2026-06-25T14:10:00.000Z',
    investigatingOfficer: 'Inspector Rekha Thomas',
    evidenceCount: 14,
    witnessCount: 6,
    offences: ['IPC 302', 'IPC 201'],
    forensicProgress: { completed: 14, total: 14 },
    cocStatus: 'Verified',
    status: 'Charge Sheet Preparation',
    lastUpdated: '2026-09-13T11:20:00.000Z',
    description: 'Homicide case against accused Anand Varma. All 14 evidence items forensically examined and reports received. Accused in judicial custody. Charge sheet under finalization for submission to court.',
    district: 'Bengaluru Central',
  },
];

// ===== MOCK EVIDENCE =====

export const MOCK_EVIDENCE: IOEvidence[] = [
  // ---- FIR 142/2026 ----
  {
    evidenceId: 'EV-0142',
    caseId: 'FIR 142/2026',
    type: 'Mobile Device',
    description: 'Black Samsung Galaxy smartphone recovered from crime scene. IMEI: 358971234567890. Screen cracked. Stored in anti-static evidence bag.',
    collectedAt: '2026-09-02T18:32:00.000Z',
    collectedLocation: 'Crime Scene A, Koramangala, Bengaluru',
    collectedBy: 'SI Arun Kumar',
    currentCustodian: 'Evidence Store Officer',
    currentLocation: 'Central Police Station Evidence Store',
    status: 'Secure Storage',
    integrityStatus: 'Verified',
    forensicStatus: 'Report Available',
    sha256Hash: 'a83f91bc4d27e9f3a1c85b67d204f9e82c3a7b164f98e2d51b4c9a230f891bc4d',
    blockchainTxId: 'TX-8F21A4B9',
    blockchainVerified: true,
    sealId: 'SEAL-9821',
    notes: 'Device found switched off. Battery removed and stored separately. Forensic examination complete; detailed digital report received from FSL Bengaluru.',
  },
  {
    evidenceId: 'EV-0143',
    caseId: 'FIR 142/2026',
    type: 'CCTV Footage',
    description: 'Digital video footage from ATM surveillance camera, 720p resolution, 2 hours duration covering 17:00–19:00 hrs on 02-Sep-2026. Copied to encrypted USB drive.',
    collectedAt: '2026-09-02T19:15:00.000Z',
    collectedLocation: 'ATM Branch, 5th Block, Koramangala, Bengaluru',
    collectedBy: 'SI Arun Kumar',
    currentCustodian: 'Evidence Store Officer',
    currentLocation: 'Digital Evidence Server, Central PS',
    status: 'Secure Storage',
    integrityStatus: 'Verified',
    forensicStatus: 'Report Available',
    sha256Hash: 'c72e4a8b19df3c5e7f2a90b43d651c8e7f1b2a9d4c56e3f8a1b72c9e4d530f7a2',
    blockchainTxId: 'TX-8F21A4C2',
    blockchainVerified: true,
    sealId: 'SEAL-9822',
    notes: 'Original footage secured at ATM branch with NOC obtained. Hash verified at time of collection and again after transfer.',
  },
  {
    evidenceId: 'EV-0144',
    caseId: 'FIR 142/2026',
    type: 'Fingerprint Lift',
    description: "Latent fingerprint lifted from victim's mobile phone case using ninhydrin spray. Lift card #FL-004-2026. Partial print, approximately 60% clarity.",
    collectedAt: '2026-09-02T20:30:00.000Z',
    collectedLocation: 'Crime Scene A, Koramangala, Bengaluru',
    collectedBy: 'Constable Ravi',
    currentCustodian: 'FSL Officer',
    currentLocation: 'FSL Bengaluru, Lab 2',
    status: 'At FSL',
    integrityStatus: 'Verified',
    forensicStatus: 'Under Examination',
    sha256Hash: 'f19c2d8e5a4b73c6e291a08d47f3b6c9e2a58d1f730b4c9e8f25a1d47b6c3e90f',
    blockchainTxId: 'TX-8F21A4D5',
    blockchainVerified: true,
    sealId: 'SEAL-9823',
    notes: 'FSL transfer acknowledged after delay; alert raised. Examination currently in progress at FSL Bengaluru.',
  },
  {
    evidenceId: 'EV-0145',
    caseId: 'FIR 142/2026',
    type: 'Blood Sample',
    description: 'Blood sample collected from crime scene floor using sterile swab kit. Sample volume approx. 5ml. Stored in sealed biohazard container at 4°C during transit.',
    collectedAt: '2026-09-02T19:45:00.000Z',
    collectedLocation: 'Crime Scene A, Koramangala, Bengaluru',
    collectedBy: 'SI Arun Kumar',
    currentCustodian: 'FSL Officer',
    currentLocation: 'FSL Bengaluru, Serology Lab',
    status: 'At FSL',
    integrityStatus: 'Verified',
    forensicStatus: 'Report Available',
    sha256Hash: 'e47b3c9d1a8f52e7b304c91a58d27b3f6c9e2a1d48b75c3e90f1a2d47b6c3e91a',
    blockchainTxId: 'TX-8F21A4E8',
    blockchainVerified: true,
    sealId: 'SEAL-9824',
    notes: 'DNA profile extracted. Serology report filed. Blood type matched. Full FSL report available.',
  },
  {
    evidenceId: 'EV-0146',
    caseId: 'FIR 142/2026',
    type: 'Written Statement',
    description: "Handwritten statement by eyewitness Mr. K. Sridhar, 3 pages, dated 03-Sep-2026. Statement corroborates CCTV footage timeline. Witness signature and IO countersignature present.",
    collectedAt: '2026-09-03T10:00:00.000Z',
    collectedLocation: 'Koramangala PS, Statement Room',
    collectedBy: 'SI Arun Kumar',
    currentCustodian: 'Evidence Store Officer',
    currentLocation: 'Evidence Store Room B, Central PS',
    status: 'Secure Storage',
    integrityStatus: 'Not Checked',
    forensicStatus: 'Not Required',
    sha256Hash: 'b93f17cd4e28f0a5c73b9e41d268c4f9a18b573e20c41b9a6f47c8e3d21f09b5c',
    blockchainTxId: 'TX-8F21A4F1',
    blockchainVerified: true,
    notes: 'Document evidence. Forensic examination not required. Stored in sealed manila envelope with case reference number.',
  },
  {
    evidenceId: 'EV-0147',
    caseId: 'FIR 142/2026',
    type: 'CCTV Footage',
    description: "Footage from suspect's building entrance camera, MP4 format, H.264 encoded, covering 15:00–23:00 hrs on 02-Sep-2026. Retrieved from DVR.",
    collectedAt: '2026-09-03T14:20:00.000Z',
    collectedLocation: 'Apartment Complex, 8th Cross, Koramangala, Bengaluru',
    collectedBy: 'Constable Ravi',
    currentCustodian: 'Evidence Store Officer',
    currentLocation: 'Digital Evidence Server, Central PS',
    status: 'Secure Storage',
    integrityStatus: 'Pending',
    forensicStatus: 'Pending Submission',
    sha256Hash: 'd25a8c4f1e7b3a9d60f2c5b8e3a7f14c9d28b5a1e7c3f9b4d6a20e5c8f1b3a74d',
    blockchainTxId: 'TX-8F21A4G3',
    blockchainVerified: false,
    sealId: 'SEAL-9830',
    notes: 'Hash verification pending. FSL submission not yet initiated. Priority item for forensic examination.',
  },
  {
    evidenceId: 'EV-0148',
    caseId: 'FIR 142/2026',
    type: 'Weapon',
    description: 'Kitchen knife, stainless steel, 20cm blade length, recovered from dustbin near crime scene. Potential trace blood on blade. Packaged in rigid evidence container.',
    collectedAt: '2026-09-02T21:05:00.000Z',
    collectedLocation: 'Municipal Dustbin, Near Crime Scene A, Koramangala',
    collectedBy: 'SI Arun Kumar',
    currentCustodian: 'FSL Officer',
    currentLocation: 'FSL Bengaluru, Trace Evidence Lab',
    status: 'At FSL',
    integrityStatus: 'Verified',
    forensicStatus: 'Report Available',
    sha256Hash: 'c84b2a9e5f1d7c3b0e8a6f4d29c7b3e5a1d8f0c6b9e4a3d7f2c0b8e5a9d4c7f3b',
    blockchainTxId: 'TX-8F21A4H7',
    blockchainVerified: true,
    sealId: 'SEAL-9825',
    notes: 'Serological analysis confirms victim blood group on blade. Fingerprint examination pending on handle.',
  },
  {
    evidenceId: 'EV-0149',
    caseId: 'FIR 142/2026',
    type: 'Physical Sample',
    description: 'Soil sample from crime scene floor and near doorstep — 2 separate sealed containers. Trace evidence analysis requested.',
    collectedAt: '2026-09-02T20:55:00.000Z',
    collectedLocation: 'Crime Scene A, Koramangala, Bengaluru',
    collectedBy: 'Constable Ravi',
    currentCustodian: 'FSL Officer',
    currentLocation: 'FSL Bengaluru, Trace Evidence Lab',
    status: 'At FSL',
    integrityStatus: 'Verified',
    forensicStatus: 'Examination Complete',
    sha256Hash: 'a91e3d7c5f2b0e8a6d4c2b9f7e3a5d1c8f6b4e2a0d8c6f4b2e0a8c6f4d2b0e8a6',
    blockchainTxId: 'TX-8F21A4I9',
    blockchainVerified: true,
    sealId: 'SEAL-9826',
    notes: 'Soil composition analysis complete. Comparison with suspect premises sample ongoing.',
  },

  // ---- FIR 089/2026 ----
  {
    evidenceId: 'EV-0200',
    caseId: 'FIR 089/2026',
    type: 'Stolen Goods',
    description: 'Gold jewellery items (6 pieces) recovered from accused — 2 necklaces, 3 bangles, 1 ring. Estimated value ₹3,20,000. Identified by complainant as stolen property.',
    collectedAt: '2026-07-15T14:00:00.000Z',
    collectedLocation: 'Accused Residence, BTM Layout, Bengaluru',
    collectedBy: 'DSP Priya Menon',
    currentCustodian: 'Evidence Store Officer',
    currentLocation: 'Koramangala PS Evidence Strong Room',
    status: 'Secure Storage',
    integrityStatus: 'Verified',
    forensicStatus: 'Not Required',
    sha256Hash: 'f4b8e2a6c0d9f3b7e1a5c9d3b7f1e5a9c3d7f1b5e9a3c7d1f5b9e3a7c1d5f9b3e7',
    blockchainTxId: 'TX-9A11B001',
    blockchainVerified: true,
    sealId: 'SEAL-8901',
    notes: 'Items photographed and catalogued. Complainant identification statement obtained.',
  },
  {
    evidenceId: 'EV-0201',
    caseId: 'FIR 089/2026',
    type: 'CCTV Footage',
    description: 'CCTV footage from complainant residence showing accused entering premises. Timestamp 2026-07-14T22:35:00. 45 minutes duration.',
    collectedAt: '2026-07-15T10:30:00.000Z',
    collectedLocation: 'Complainant Residence, 12th Main, Koramangala',
    collectedBy: 'DSP Priya Menon',
    currentCustodian: 'Evidence Store Officer',
    currentLocation: 'Digital Evidence Server, Koramangala PS',
    status: 'Secure Storage',
    integrityStatus: 'Verified',
    forensicStatus: 'Report Available',
    sha256Hash: 'a3c7f1b5e9d4c8f2b6e0a4c8d2f6b0e4a8c2d6f0b4e8a2c6d0f4b8e2a6c0d4f8b2',
    blockchainTxId: 'TX-9A11B002',
    blockchainVerified: true,
    notes: 'Facial recognition analysis confirms accused. Transfer to FSL acknowledged. Report received.',
  },
  {
    evidenceId: 'EV-0202',
    caseId: 'FIR 089/2026',
    type: 'Fingerprint Lift',
    description: 'Fingerprint lifts from window latch (point of entry). 3 latent prints of good quality collected. Matched to accused fingerprint record.',
    collectedAt: '2026-07-15T12:00:00.000Z',
    collectedLocation: 'Complainant Residence, Window Frame, 12th Main, Koramangala',
    collectedBy: 'DSP Priya Menon',
    currentCustodian: 'Evidence Store Officer',
    currentLocation: 'Koramangala PS Evidence Store',
    status: 'Secure Storage',
    integrityStatus: 'Verified',
    forensicStatus: 'Report Available',
    sha256Hash: 'b5d9e3a7c1f5b9e3a7c1d5f9b3e7a1c5d9f3b7e1a5c9d3f7b1e5a9c3f7d1b5e9a3',
    blockchainTxId: 'TX-9A11B003',
    blockchainVerified: true,
    sealId: 'SEAL-8902',
    notes: 'AFIS match confirmed accused identity. Report on file.',
  },
  {
    evidenceId: 'EV-0203',
    caseId: 'FIR 089/2026',
    type: 'Accused Clothing',
    description: "Clothing worn by accused at time of arrest — blue denim shirt and black trousers. Submitted for trace evidence comparison with complainant's residence.",
    collectedAt: '2026-07-15T15:45:00.000Z',
    collectedLocation: 'Koramangala PS, Arrest Spot',
    collectedBy: 'DSP Priya Menon',
    currentCustodian: 'Evidence Store Officer',
    currentLocation: 'Koramangala PS Evidence Store',
    status: 'Secure Storage',
    integrityStatus: 'Verified',
    forensicStatus: 'Report Available',
    sha256Hash: 'c7f1b5e9a3d7f1b5e9a3c7d1f5b9e3a7c1d5f9b3e7a1c5d9f3b7e1a5c9d3f7b1e5',
    blockchainTxId: 'TX-9A11B004',
    blockchainVerified: true,
    sealId: 'SEAL-8903',
    notes: 'Trace soil matching crime scene found on trouser cuff. Report verified.',
  },

  // ---- FIR 201/2026 ----
  {
    evidenceId: 'EV-0300',
    caseId: 'FIR 201/2026',
    type: 'Mobile Device',
    description: 'iPhone 14 Pro, black, recovered from accused Pradeep Sharma during raid. Contains suspected fraudulent UPI transaction records. Stored in Faraday bag.',
    collectedAt: '2026-09-08T15:30:00.000Z',
    collectedLocation: 'Accused Flat, HSR Layout, Sector 4, Bengaluru',
    collectedBy: 'SI Vikram Nair',
    currentCustodian: 'FSL Officer',
    currentLocation: 'FSL Bengaluru, Cyber Forensics Lab',
    status: 'At FSL',
    integrityStatus: 'Verified',
    forensicStatus: 'Under Examination',
    sha256Hash: 'd9f3b7e1a5c9d3f7b1e5a9c3d7f1b5e9a3c7d1f5b9e3a7c1d5f9b3e7a1c5d9f3b7',
    blockchainTxId: 'TX-7C34D001',
    blockchainVerified: true,
    sealId: 'SEAL-2011',
    notes: 'Stored in Faraday cage at all times to prevent remote wipe. Passcode extraction attempted; pending FSL analysis.',
  },
  {
    evidenceId: 'EV-0301',
    caseId: 'FIR 201/2026',
    type: 'Laptop Computer',
    description: 'Dell Inspiron 15 laptop, silver, S/N: CN0AB1234567. Contains spreadsheets and email records related to suspected fraudulent transactions worth ₹2.4 crore.',
    collectedAt: '2026-09-08T15:45:00.000Z',
    collectedLocation: 'Accused Flat, HSR Layout, Sector 4, Bengaluru',
    collectedBy: 'SI Vikram Nair',
    currentCustodian: 'FSL Officer',
    currentLocation: 'FSL Bengaluru, Cyber Forensics Lab',
    status: 'At FSL',
    integrityStatus: 'Verified',
    forensicStatus: 'Under Examination',
    sha256Hash: 'e1a5c9d3f7b1e5a9c3d7f1b5e9a3c7d1f5b9e3a7c1d5f9b3e7a1c5d9f3b7e1a5c9',
    blockchainTxId: 'TX-7C34D002',
    blockchainVerified: true,
    sealId: 'SEAL-2012',
    notes: 'Bit-by-bit forensic image taken before examination. Original hard drive sealed separately.',
  },
  {
    evidenceId: 'EV-0312',
    caseId: 'FIR 201/2026',
    type: 'Bank Documents',
    description: 'Forged bank statements and identity documents — 12 pages. Suspected fabrication of Aadhaar and PAN cards for multiple identities.',
    collectedAt: '2026-09-09T11:00:00.000Z',
    collectedLocation: 'HSR Layout PS, Seized from accused associate',
    collectedBy: 'Constable K. Bharat',
    currentCustodian: 'Evidence Store Officer',
    currentLocation: 'HSR Layout PS Evidence Store',
    status: 'Secure Storage',
    integrityStatus: 'Pending',
    forensicStatus: 'Pending Submission',
    sha256Hash: 'f3b7e1a5c9d3f7b1e5a9c3d7f1b5e9a3c7d1f5b9e3a7c1d5f9b3e7a1c5d9f3b7e1',
    blockchainTxId: 'TX-7C34D012',
    blockchainVerified: false,
    notes: 'Receipt logged without matching dispatch event. Alert raised. Integrity check pending. Document examiner referral requested.',
  },
];

// ===== MOCK CUSTODY TIMELINE =====

export const MOCK_CUSTODY_TIMELINE: CustodyEvent[] = [
  // ---- EV-0142 ----
  {
    id: 'CE-0001',
    evidenceId: 'EV-0142',
    timestamp: '2026-09-02T18:32:00.000Z',
    eventType: 'Evidence Collected',
    actor: 'SI Arun Kumar',
    toCustodian: 'SI Arun Kumar',
    location: 'Crime Scene A, Koramangala, Bengaluru',
    txId: 'TX-8F21A001',
    blockchainVerified: true,
    notes: 'Mobile device collected in switched-off condition. Placed in anti-static evidence bag.',
  },
  {
    id: 'CE-0002',
    evidenceId: 'EV-0142',
    timestamp: '2026-09-02T18:45:00.000Z',
    eventType: 'Evidence Sealed',
    actor: 'SI Arun Kumar',
    location: 'Crime Scene A, Koramangala, Bengaluru',
    txId: 'TX-8F21A002',
    blockchainVerified: true,
    sealId: 'SEAL-9821',
    notes: 'Evidence sealed with tamper-evident seal. Seal number recorded and photographed.',
  },
  {
    id: 'CE-0003',
    evidenceId: 'EV-0142',
    timestamp: '2026-09-02T19:20:00.000Z',
    eventType: 'Custody Transferred',
    actor: 'SI Arun Kumar',
    fromCustodian: 'SI Arun Kumar',
    toCustodian: 'Constable Ravi',
    location: 'Koramangala PS',
    txId: 'TX-8F21A003',
    blockchainVerified: true,
    notes: 'Transfer for escort to Central PS Evidence Store. Seal integrity confirmed prior to transfer.',
  },
  {
    id: 'CE-0004',
    evidenceId: 'EV-0142',
    timestamp: '2026-09-02T20:05:00.000Z',
    eventType: 'Custody Received',
    actor: 'Constable Ravi',
    fromCustodian: 'SI Arun Kumar',
    toCustodian: 'Constable Ravi',
    location: 'Koramangala PS',
    txId: 'TX-8F21A004',
    blockchainVerified: true,
    notes: 'Receipt acknowledged. Seal SEAL-9821 intact. Evidence logged in register.',
  },
  {
    id: 'CE-0005',
    evidenceId: 'EV-0142',
    timestamp: '2026-09-03T09:15:00.000Z',
    eventType: 'Transferred to FSL',
    actor: 'Constable Ravi',
    fromCustodian: 'Constable Ravi',
    toCustodian: 'FSL Bengaluru',
    location: 'Central PS Evidence Store, Bengaluru',
    txId: 'TX-8F21A005',
    blockchainVerified: true,
    notes: 'Dispatched to FSL Bengaluru under Requisition No. FSL-REQ-2026-4421. Seal intact.',
  },
  {
    id: 'CE-0006',
    evidenceId: 'EV-0142',
    timestamp: '2026-09-03T11:42:00.000Z',
    eventType: 'Received by FSL',
    actor: 'FSL Officer Subramaniam',
    fromCustodian: 'Constable Ravi',
    toCustodian: 'FSL Officer Subramaniam',
    location: 'FSL Bengaluru, Lab 3',
    txId: 'TX-8F21A006',
    blockchainVerified: true,
    notes: 'Received and logged. Seal SEAL-9821 verified intact. Assigned for digital forensics examination.',
  },
  {
    id: 'CE-0007',
    evidenceId: 'EV-0142',
    timestamp: '2026-09-04T14:30:00.000Z',
    eventType: 'Forensic Examination Started',
    actor: 'Dr. Anitha Krishnan',
    location: 'FSL Bengaluru, Lab 3',
    txId: 'TX-8F21A007',
    blockchainVerified: true,
    notes: 'Digital forensics examination commenced. Forensic imaging of device storage initiated.',
  },
  {
    id: 'CE-0008',
    evidenceId: 'EV-0142',
    timestamp: '2026-09-10T16:00:00.000Z',
    eventType: 'Forensic Report Filed',
    actor: 'Dr. Anitha Krishnan',
    location: 'FSL Bengaluru',
    txId: 'TX-8F21A008',
    blockchainVerified: true,
    notes: 'Forensic examination complete. Detailed report filed under FSL-BLR-2026-4421. Call logs, messages, and deleted data recovered.',
  },

  // ---- EV-0143 ----
  {
    id: 'CE-0010',
    evidenceId: 'EV-0143',
    timestamp: '2026-09-02T19:15:00.000Z',
    eventType: 'Evidence Collected',
    actor: 'SI Arun Kumar',
    toCustodian: 'SI Arun Kumar',
    location: 'ATM Branch, 5th Block, Koramangala, Bengaluru',
    txId: 'TX-8F21B001',
    blockchainVerified: true,
    notes: 'Video footage copied to encrypted USB drive. Hash computed at source.',
  },
  {
    id: 'CE-0011',
    evidenceId: 'EV-0143',
    timestamp: '2026-09-02T19:30:00.000Z',
    eventType: 'Evidence Sealed',
    actor: 'SI Arun Kumar',
    location: 'ATM Branch, 5th Block, Koramangala, Bengaluru',
    txId: 'TX-8F21B002',
    blockchainVerified: true,
    sealId: 'SEAL-9822',
    notes: 'USB drive placed in tamper-evident bag and sealed.',
  },
  {
    id: 'CE-0012',
    evidenceId: 'EV-0143',
    timestamp: '2026-09-02T21:00:00.000Z',
    eventType: 'Custody Transferred',
    actor: 'SI Arun Kumar',
    fromCustodian: 'SI Arun Kumar',
    toCustodian: 'Evidence Store Officer',
    location: 'Central PS Evidence Store, Bengaluru',
    txId: 'TX-8F21B003',
    blockchainVerified: true,
    notes: 'Transferred to Central PS Digital Evidence Server for secure storage.',
  },
  {
    id: 'CE-0013',
    evidenceId: 'EV-0143',
    timestamp: '2026-09-03T09:00:00.000Z',
    eventType: 'Transferred to FSL',
    actor: 'Evidence Store Officer',
    fromCustodian: 'Evidence Store Officer',
    toCustodian: 'FSL Bengaluru',
    location: 'Central PS Evidence Store, Bengaluru',
    txId: 'TX-8F21B004',
    blockchainVerified: true,
    notes: 'Digital copy transferred to FSL via secure encrypted channel. FSL requisition FSL-BLR-2026-4422 raised.',
  },

  // ---- EV-0144 ----
  {
    id: 'CE-0020',
    evidenceId: 'EV-0144',
    timestamp: '2026-09-02T20:30:00.000Z',
    eventType: 'Evidence Collected',
    actor: 'Constable Ravi',
    toCustodian: 'Constable Ravi',
    location: 'Crime Scene A, Koramangala, Bengaluru',
    txId: 'TX-8F21C001',
    blockchainVerified: true,
    notes: 'Fingerprint lift collected using ninhydrin spray. Lift card labelled and photographed.',
  },
  {
    id: 'CE-0021',
    evidenceId: 'EV-0144',
    timestamp: '2026-09-02T20:45:00.000Z',
    eventType: 'Evidence Sealed',
    actor: 'Constable Ravi',
    location: 'Crime Scene A, Koramangala, Bengaluru',
    txId: 'TX-8F21C002',
    blockchainVerified: true,
    sealId: 'SEAL-9823',
    notes: 'Lift card placed in protective sleeve and sealed.',
  },
  {
    id: 'CE-0022',
    evidenceId: 'EV-0144',
    timestamp: '2026-09-02T21:30:00.000Z',
    eventType: 'Custody Transferred',
    actor: 'Constable Ravi',
    fromCustodian: 'Constable Ravi',
    toCustodian: 'Evidence Store Officer',
    location: 'Koramangala PS',
    txId: 'TX-8F21C003',
    blockchainVerified: true,
    notes: 'Transferred to PS evidence store overnight before FSL dispatch.',
  },
  {
    id: 'CE-0023',
    evidenceId: 'EV-0144',
    timestamp: '2026-09-04T08:30:00.000Z',
    eventType: 'Transferred to FSL',
    actor: 'Evidence Store Officer',
    fromCustodian: 'Evidence Store Officer',
    toCustodian: 'FSL Bengaluru',
    location: 'Central PS Evidence Store, Bengaluru',
    txId: 'TX-8F21C004',
    blockchainVerified: true,
    notes: 'Dispatched under FSL-REQ-2026-4435. Alert raised for delayed acknowledgement.',
  },
  {
    id: 'CE-0024',
    evidenceId: 'EV-0144',
    timestamp: '2026-09-04T11:15:00.000Z',
    eventType: 'Received by FSL',
    actor: 'FSL Officer Subramaniam',
    fromCustodian: 'Evidence Store Officer',
    toCustodian: 'FSL Officer Subramaniam',
    location: 'FSL Bengaluru, Lab 2',
    txId: 'TX-8F21C005',
    blockchainVerified: true,
    notes: 'Receipt confirmed after 12-hour delay. Seal SEAL-9823 intact. AFIS examination queued.',
  },
];

// ===== MOCK FORENSIC RECORDS =====

export const MOCK_FORENSIC_RECORDS: ForensicRecord[] = [
  {
    evidenceId: 'EV-0142',
    caseId: 'FIR 142/2026',
    fslRef: 'FSL-BLR-2026-4421',
    fslName: 'FSL Bengaluru',
    submittedDate: '2026-09-03T09:15:00.000Z',
    receivedDate: '2026-09-03T11:42:00.000Z',
    examinationStartDate: '2026-09-04T14:30:00.000Z',
    expectedCompletionDate: '2026-09-11T17:00:00.000Z',
    completionDate: '2026-09-10T16:00:00.000Z',
    examinationStatus: 'Report Available',
    reportHash: 'f8a2c6d9b3e7a1c5f9d3b7e1a5c9d3f7b1e5a9c3f7d1b5e9a3c7f1b5e9d3c7f1b5',
    reportBlockchainTxId: 'TX-8F21A008',
    reportBlockchainVerified: true,
    examiner: 'Dr. Anitha Krishnan',
    findings: 'Forensic imaging of device storage recovered 1,204 call records, 847 SMS messages, 23 deleted WhatsApp conversations, and 312 photographs. Key contact identified as suspect. GPS metadata from photographs places device at crime scene on 02-Sep-2026 at 18:10 hrs. Full report submitted to IO.',
  },
  {
    evidenceId: 'EV-0143',
    caseId: 'FIR 142/2026',
    fslRef: 'FSL-BLR-2026-4422',
    fslName: 'FSL Bengaluru',
    submittedDate: '2026-09-03T09:00:00.000Z',
    receivedDate: '2026-09-04T10:00:00.000Z',
    examinationStartDate: '2026-09-05T09:30:00.000Z',
    expectedCompletionDate: '2026-09-13T17:00:00.000Z',
    completionDate: '2026-09-12T15:00:00.000Z',
    examinationStatus: 'Report Available',
    reportHash: 'a1b5c9d3e7f1a5b9c3d7e1f5a9b3c7d1e5f9a3b7c1d5e9f3a7b1c5d9e3f7a1b5c9',
    reportBlockchainTxId: 'TX-8F21B010',
    reportBlockchainVerified: true,
    examiner: 'Dr. Ramesh Bhat',
    findings: 'CCTV footage analysis confirmed individual matching suspect description entering ATM premises at 18:22 hrs on 02-Sep-2026. Facial biometric comparison performed. Report with enhanced stills submitted.',
  },
  {
    evidenceId: 'EV-0144',
    caseId: 'FIR 142/2026',
    fslRef: 'FSL-BLR-2026-4435',
    fslName: 'FSL Bengaluru',
    submittedDate: '2026-09-04T08:30:00.000Z',
    receivedDate: '2026-09-04T11:15:00.000Z',
    examinationStartDate: '2026-09-07T10:00:00.000Z',
    expectedCompletionDate: '2026-09-14T17:00:00.000Z',
    examinationStatus: 'Under Examination',
    examiner: 'Dr. Sunitha Rao',
    findings: undefined,
  },
  {
    evidenceId: 'EV-0145',
    caseId: 'FIR 142/2026',
    fslRef: 'FSL-BLR-2026-4423',
    fslName: 'FSL Bengaluru',
    submittedDate: '2026-09-03T09:15:00.000Z',
    receivedDate: '2026-09-03T11:45:00.000Z',
    examinationStartDate: '2026-09-03T14:00:00.000Z',
    expectedCompletionDate: '2026-09-09T17:00:00.000Z',
    completionDate: '2026-09-08T16:30:00.000Z',
    examinationStatus: 'Report Available',
    reportHash: 'c3d7f1b5e9a3c7d1f5b9e3a7c1d5f9b3e7a1c5d9f3b7e1a5c9d3f7b1e5a9c3d7f1',
    reportBlockchainTxId: 'TX-8F21D001',
    reportBlockchainVerified: true,
    examiner: 'Dr. Lakshmi Prasad',
    findings: 'DNA profiling complete. Blood group O+. DNA profile extracted and loaded into NDNAD. Comparison with suspect DNA sample pending accused apprehension.',
  },
  {
    evidenceId: 'EV-0147',
    caseId: 'FIR 142/2026',
    fslRef: '',
    fslName: 'FSL Bengaluru',
    submittedDate: '',
    examinationStatus: 'Pending Submission',
    findings: undefined,
  },
];

// ===== MOCK ALERTS =====

export const MOCK_ALERTS: IOAlert[] = [
  {
    id: 'ALT-001',
    severity: 'critical',
    type: 'Integrity Mismatch',
    caseId: 'FIR 215/2026',
    evidenceId: 'EV-0215',
    title: 'Integrity Mismatch Detected',
    description: 'SHA-256 hash of EV-0215 does not match ledger record. Current hash differs in 4 trailing characters. Possible evidence tampering or file corruption. Immediate verification required.',
    timestamp: '2026-09-16T08:15:00.000Z',
    status: 'Open',
  },
  {
    id: 'ALT-002',
    severity: 'critical',
    type: 'Unauthorized Access',
    caseId: 'FIR 178/2026',
    title: 'Unauthorized Evidence Access Attempt',
    description: 'Unauthorized modification attempt detected on evidence records for FIR 178/2026. Access from unregistered terminal at 03:47 hrs. Three failed authentication attempts before access log was triggered.',
    timestamp: '2026-09-16T03:47:00.000Z',
    status: 'Open',
  },
  {
    id: 'ALT-003',
    severity: 'warning',
    type: 'Transfer Unacknowledged',
    caseId: 'FIR 142/2026',
    evidenceId: 'EV-0144',
    title: 'Transfer Awaiting Acknowledgement',
    description: 'FSL transfer of EV-0144 (Fingerprint Lift) has not been acknowledged for over 12 hours. Transferred on 04-Sep-2026 at 08:30. IO should follow up with FSL Bengaluru to confirm receipt.',
    timestamp: '2026-09-04T20:30:00.000Z',
    status: 'Open',
  },
  {
    id: 'ALT-004',
    severity: 'warning',
    type: 'Forensic Overdue',
    caseId: 'FIR 201/2026',
    title: 'Forensic Report Overdue',
    description: '3 evidence items for FIR 201/2026 have exceeded expected forensic completion date. Items: EV-0300, EV-0301, EV-0310. Expected completion was 2026-09-14. Contact FSL Bengaluru for status update.',
    timestamp: '2026-09-15T09:00:00.000Z',
    status: 'Open',
  },
  {
    id: 'ALT-005',
    severity: 'warning',
    type: 'Chain of Custody Exception',
    caseId: 'FIR 201/2026',
    evidenceId: 'EV-0312',
    title: 'Evidence Received Without Dispatch Event',
    description: 'EV-0312 (Bank Documents) was logged as received at HSR Layout PS Evidence Store without a corresponding dispatch event. Chain-of-custody gap detected. Review and reconcile custody records.',
    timestamp: '2026-09-09T13:00:00.000Z',
    status: 'Acknowledged',
  },
  {
    id: 'ALT-006',
    severity: 'info',
    type: 'Forensic Report',
    caseId: 'FIR 142/2026',
    evidenceId: 'EV-0142',
    title: 'Forensic Report Available',
    description: 'Forensic examination report for EV-0142 (Mobile Device) has been filed by Dr. Anitha Krishnan at FSL Bengaluru. Report verified on blockchain (TX-8F21A008). Report available for IO review.',
    timestamp: '2026-09-10T16:00:00.000Z',
    status: 'Resolved',
  },
  {
    id: 'ALT-007',
    severity: 'info',
    type: 'Transfer Acknowledged',
    caseId: 'FIR 089/2026',
    evidenceId: 'EV-0201',
    title: 'Evidence Successfully Transferred',
    description: 'Transfer of EV-0201 (CCTV Footage) for FIR 089/2026 acknowledged by receiving custodian. Chain-of-custody intact. Blockchain verification successful.',
    timestamp: '2026-09-12T10:30:00.000Z',
    status: 'Resolved',
  },
];

// ===== MOCK AUDIT EVENTS =====

export const MOCK_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'AUD-001',
    timestamp: '2026-09-02T10:00:00.000Z',
    user: 'SI Arun Kumar',
    action: 'User Login',
    caseId: undefined,
    txId: 'TX-8F21AA01',
    verificationStatus: 'Verified',
    details: 'Successful login from PS terminal. Session initiated for FIR 142/2026 investigation.',
    role: 'Investigating Officer',
  },
  {
    id: 'AUD-002',
    timestamp: '2026-09-02T18:35:00.000Z',
    user: 'SI Arun Kumar',
    action: 'Evidence Registered',
    evidenceId: 'EV-0142',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA02',
    verificationStatus: 'Verified',
    details: 'Mobile device EV-0142 registered in system. SHA-256 hash computed and recorded on blockchain.',
    role: 'Investigating Officer',
  },
  {
    id: 'AUD-003',
    timestamp: '2026-09-02T18:48:00.000Z',
    user: 'SI Arun Kumar',
    action: 'Evidence Sealed',
    evidenceId: 'EV-0142',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA03',
    verificationStatus: 'Verified',
    details: 'Evidence EV-0142 sealed with SEAL-9821. Sealing event recorded on blockchain.',
    role: 'Investigating Officer',
  },
  {
    id: 'AUD-004',
    timestamp: '2026-09-02T19:18:00.000Z',
    user: 'SI Arun Kumar',
    action: 'Evidence Registered',
    evidenceId: 'EV-0143',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA04',
    verificationStatus: 'Verified',
    details: 'CCTV footage EV-0143 registered. Digital evidence hash computed at collection site.',
    role: 'Investigating Officer',
  },
  {
    id: 'AUD-005',
    timestamp: '2026-09-02T20:33:00.000Z',
    user: 'Constable Ravi',
    action: 'Evidence Registered',
    evidenceId: 'EV-0144',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA05',
    verificationStatus: 'Verified',
    details: 'Fingerprint lift EV-0144 registered. Collection details logged.',
    role: 'Constable',
  },
  {
    id: 'AUD-006',
    timestamp: '2026-09-02T19:48:00.000Z',
    user: 'SI Arun Kumar',
    action: 'Evidence Registered',
    evidenceId: 'EV-0145',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA06',
    verificationStatus: 'Verified',
    details: 'Blood sample EV-0145 registered. Biohazard handling protocols recorded.',
    role: 'Investigating Officer',
  },
  {
    id: 'AUD-007',
    timestamp: '2026-09-02T19:22:00.000Z',
    user: 'SI Arun Kumar',
    action: 'Custody Transfer Initiated',
    evidenceId: 'EV-0142',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA07',
    verificationStatus: 'Verified',
    details: 'Custody of EV-0142 transferred from SI Arun Kumar to Constable Ravi for escort to PS Evidence Store.',
    role: 'Investigating Officer',
  },
  {
    id: 'AUD-008',
    timestamp: '2026-09-02T20:07:00.000Z',
    user: 'Constable Ravi',
    action: 'Custody Receipt Acknowledged',
    evidenceId: 'EV-0142',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA08',
    verificationStatus: 'Verified',
    details: 'Receipt of EV-0142 acknowledged by Constable Ravi. Seal SEAL-9821 integrity verified.',
    role: 'Constable',
  },
  {
    id: 'AUD-009',
    timestamp: '2026-09-03T09:10:00.000Z',
    user: 'SI Arun Kumar',
    action: 'Evidence Registered',
    evidenceId: 'EV-0146',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA09',
    verificationStatus: 'Verified',
    details: 'Eyewitness written statement EV-0146 registered. Document stored in sealed envelope.',
    role: 'Investigating Officer',
  },
  {
    id: 'AUD-010',
    timestamp: '2026-09-03T09:18:00.000Z',
    user: 'Evidence Store Officer',
    action: 'FSL Transfer Initiated',
    evidenceId: 'EV-0142',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA10',
    verificationStatus: 'Verified',
    details: 'EV-0142 dispatched to FSL Bengaluru under requisition FSL-REQ-2026-4421. Seal verified before dispatch.',
    role: 'Evidence Store Officer',
  },
  {
    id: 'AUD-011',
    timestamp: '2026-09-03T09:05:00.000Z',
    user: 'Evidence Store Officer',
    action: 'FSL Transfer Initiated',
    evidenceId: 'EV-0143',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA11',
    verificationStatus: 'Verified',
    details: 'EV-0143 digital evidence transferred to FSL via secure channel. FSL requisition FSL-BLR-2026-4422 created.',
    role: 'Evidence Store Officer',
  },
  {
    id: 'AUD-012',
    timestamp: '2026-09-03T11:44:00.000Z',
    user: 'FSL Officer Subramaniam',
    action: 'FSL Receipt Confirmed',
    evidenceId: 'EV-0142',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA12',
    verificationStatus: 'Verified',
    details: 'Receipt of EV-0142 confirmed by FSL Bengaluru. Logged under FSL-BLR-2026-4421.',
    role: 'FSL Officer',
  },
  {
    id: 'AUD-013',
    timestamp: '2026-09-03T14:25:00.000Z',
    user: 'Constable Ravi',
    action: 'Evidence Registered',
    evidenceId: 'EV-0147',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA13',
    verificationStatus: 'Pending',
    details: 'CCTV footage EV-0147 registered from apartment complex. Hash verification pending.',
    role: 'Constable',
  },
  {
    id: 'AUD-014',
    timestamp: '2026-09-04T08:32:00.000Z',
    user: 'Evidence Store Officer',
    action: 'FSL Transfer Initiated',
    evidenceId: 'EV-0144',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA14',
    verificationStatus: 'Verified',
    details: 'EV-0144 dispatched to FSL Bengaluru under FSL-REQ-2026-4435. Alert pending for acknowledgement.',
    role: 'Evidence Store Officer',
  },
  {
    id: 'AUD-015',
    timestamp: '2026-09-10T16:05:00.000Z',
    user: 'SI Arun Kumar',
    action: 'Forensic Report Viewed',
    evidenceId: 'EV-0142',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA15',
    verificationStatus: 'Verified',
    details: 'IO accessed forensic report for EV-0142. Report hash verified against blockchain record TX-8F21A008.',
    role: 'Investigating Officer',
  },
  {
    id: 'AUD-016',
    timestamp: '2026-09-10T16:10:00.000Z',
    user: 'SI Arun Kumar',
    action: 'Integrity Verification Run',
    evidenceId: 'EV-0142',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA16',
    verificationStatus: 'Verified',
    details: 'Manual integrity verification run on EV-0142. Hash match confirmed. Blockchain record consistent.',
    role: 'Investigating Officer',
  },
  {
    id: 'AUD-017',
    timestamp: '2026-09-15T14:22:00.000Z',
    user: 'SI Arun Kumar',
    action: 'Case Status Updated',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA17',
    verificationStatus: 'Verified',
    details: 'Case status remains Under Investigation. Progress note added: awaiting FSL report for EV-0144.',
    role: 'Investigating Officer',
  },
  {
    id: 'AUD-018',
    timestamp: '2026-09-16T08:00:00.000Z',
    user: 'SI Arun Kumar',
    action: 'User Login',
    caseId: 'FIR 142/2026',
    txId: 'TX-8F21AA18',
    verificationStatus: 'Verified',
    details: 'Morning login. Dashboard accessed for FIR 142/2026 review.',
    role: 'Investigating Officer',
  },
];
